# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 01:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.PositiveIntegerField(verbose_name='Repository ID')),
                ('name', models.CharField(max_length=128, verbose_name='Repository name')),
                ('url', models.URLField(verbose_name='Repository URL')),
                ('language', models.CharField(max_length=32)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None)),
            ],
        ),
    ]
